server: 
  compression:
    enabled: true
    min-response-size: 2048 # 默认值
    mime-types:
    - text/html
    - text/plain
    - application/json
spring:
  datasource:
    name: development
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/db_springboot_mybatis?unicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #cachePrepStmts: true # 开启二级缓存
  redis:
#    database: 0
#    host: 192.168.199.143
#    port: 6379
    password: 
    pool:
      max-active: 1000 # 连接池最大连接数
      max-wait: -1 # 最大等待阻塞时间
      max-idle: 100 # 最大空闲连接
      min-idle: 10 # 最小空闲连接
    timeout: 0 # 连接超时时间
    cluster:
      nodes:
      - 192.168.199.143:10001
      - 192.168.199.143:10002
      - 192.168.199.143:10003
      - 192.168.199.143:10004
      - 192.168.199.143:10005
      - 192.168.199.143:10006
      max-redirects: 6
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.haven.framework.springboot.mybatis.domain